import React, {Component} from 'react';

export default class Privacy extends Component {
  render() {
    return (
      <div>
      <h1>Privacy Policy</h1>
      <p>Your privacy is very important to us at Chyp and we know that you care how information about you is used and shared. This Privacy Policy governs the website located at www.chyp.ca and any other websites and services owned or operated by Chyp (collectively, “Website”). The Policy outlines what information we collect, how we use it, and under what circumstances, if any, we will share it. Other than as set forth in this Policy, Chyp will not provide your Personally Identifiable         Information (defined below) to third parties without your specific permission.<br/>
            <br/>By visiting the Chyp Website, submitting information, or using any of our products or services, you acknowledge that you have read and agree to be bound by the terms of this Privacy Policy and you consent to having your data transferred to, and processed in, the United States. This policy may change from time to time. Your continued use of this Website after we make changes is deemed to be acceptance of those changes, so please check the policy periodically for updates. If you do not agree, you should exit the Website and not use any of our products or services or provide any information.
            <br/>Throughout this Privacy Policy we may refer to Chyp as “us” or “we,” and we may refer to you as “you,” the “user” or “end user.”
            <br/>1. Applicability of Policy. This policy applies to information we collect: on this Website; in e-mail, text and other electronic messages between you and this Website; through any mobile and desktop applications created by Chyp.
            <br/>2. Exclusions from Policy. This policy does not apply to information collected by us offline or through any other means, including information collected on any other website operated by Chyp or any third party (including our affiliates and subsidiaries). The policy also does not apply to any information collected through any application or content (including advertising) that may link to or be accessible from or on the Website]
            <br/>3. Types of Information Collected. The information we learn from users helps us personalize and continually improve our offerings and your experience with Chyp, such as by customizing content (including advertising content), responding to e-mail requests, and communicating with you. We gather two basic types of information: “Personally Identifiable Information” that can identify a person as an individual (e.g., name, mailing address, telephone number, e-mail address) and “Non-Personally Identifiable Information,” which may include aggregated information, demographic information, IP addresses, and any other information that does not necessarily reveal a person’s specific identity. Within those two broad categories, we gather information as follows.
            <br/>1. Information You Provide to Us. We may receive and store any information you enter on our Website or provide to us in any way. This may include information you provide in your profile or registration, information that you provide when filling in forms on our Website, or any other information that you provide to us; this may include your first and last name, nickname, e-mail address, mailing address, password, telephone number, date of birth, organization name, or organization type. You may also provide us information when: ordering a product or service (and this may include your credit card and related information), entering a contest or sweepstake, filling out a survey, posting a review or comment, providing feedback, requesting information, corresponding with us, sending messages, posting materials, performing searches, or requesting further services. Some or all of the functionality contemplated in the preceding sentence may or may not be available at any given time. You may choose not to provide us with certain information, but that may prevent you from: participating in or using the activity or service (e.g., e-mail alerts), posting comments to our Website, creating a user profile, performing searches or queries, sending messages, purchasing products or services, or communicating with us.
            <br/>2. Cookies. A cookie is a small file that is stored on a user’s computer for record-keeping purposes that contains information about that user. We may use cookies to: save you time while using the Website, remind us who you are, and track and target user interests in order to provide a customized experience. Cookies may also allow us to gather Non-Personally Identifiable Information from you, like the web pages you have visited and the links you have clicked on. We use this information to help us create a more user-friendly experience for all visitors. In addition, we may use third-party advertising companies to place advertisements on our Website. As part of their service, those third-party advertisers may use cookies (either alone or in conjunction with web beacons or other tracking technologies) to collect information about our users. This may include information about users’ behavior on this and other websites to serve them interest-based (i.e., behavioral) advertising. We have no access to and do not control these third parties’ tracking technologies or how they may be used. This Privacy Policy covers the use of cookies by our Website only and does not cover the use of cookies by any advertiser or other third party. If you have any questions about an advertisement, you should contact the responsible advertiser directly.
            <br/>3. Settings for Cookies. Most browsers automatically accept cookies, but you may be able to modify your browser settings to decline cookies (the “help” portion of the toolbar on the majority of browsers will direct you on how to prevent your browser from accepting new cookies, how to command the browser to tell you when you receive a new cookie, or how to fully disable cookies). But we encourage you to leave the cookies activated because cookies may enable you to take advantage of some of Chyp’s features and if you decline or delete cookies, parts of the Website may not work effectively or at all.
            <br/>4. Web Beacons, etc. In addition to cookies, we may use other technologies like web beacons and pixel tags to track your use of our Website pages and promotions, or we may allow our Third-Party Service Providers to use these devices on our behalf. Web beacons and pixel tags are small electronic files (also sometimes referred to “clear gifs” and and “single-pixel gifs”) placed on websites or in e-mails that indicate whether you have performed a specific action. When you access these pages or open or click an e-mail, a web beacon or pixel tag may generate a notice of that action. Web beacons and pixel tags may provide information about visitor traffic and behavior on our Website and provide a way to measure the effectiveness of any marketing or promotions. We may also utilize web beacons and pixel tags provided by our affiliated businesses for the same purposes.
            <br/>5. Automatic Information. We may receive and store certain types of information whenever you interact with us. For example, like many web sites and as addressed above, we may use “cookies,” and we may automatically collect certain types of information when your Web browser accesses our Website or advertisements and other content served by or on behalf of us on other sites. This may include information about your operating system and browser, sites accessed before accessing our Website, websites accessed after leaving our Website, your IP address, information about your Internet connection, pages you requested, preferences, and history. Generally, our Website may automatically collect usage information, such as the numbers and frequency of visitors to our Website and its components.
            <br/>6. E-mail Communications. We may receive confirmation via HTML code when you open an e-mail from us. We may use that information to measure the effectiveness of our Website and offerings and reduce or eliminate duplicate e-mails. If you no longer wish to receive promotional e-mails from us, please unsubscribe or change your profile settings. Even if you opt-out of promotional e-mails, however, we may continue to send you any necessary administrative or transactional e-mails, such as those regarding purchase transactions.
            <br/>7. Information from Other Sources. We may receive information about you from other sources and add it to our account information to help personalize our offerings.
            <br/>4. Uses of Personally-Identifiable Information. We may use information that we collect about you or that you provide to us, including any personal information in the following ways:
            <br/>1. To provide you with notices about your account, including expiration and renewal notices, and otherwise contact you about our goods and services that may be of interest to you.
            <br/>2. To provide you with information, services, or products that you request from us.
            <br/>3. To present the contents of our Website to you, analyze Website use, troubleshoot our Website, and enhance the operation of the Website.
            <br/>4. To troubleshoot our products and services.
            <br/>5. To improve our marketing and promotional efforts.
            <br/>6. To administer sweepstakes and contests.
            <br/>7. To enable us to display advertisements to our advertisers’ target audiences and measure the effectiveness of those advertisements. (Even though we do not disclose your personal information for these purposes without your consent, if you click on or otherwise interact with an advertisement, the advertiser may assume that you meet its target criteria.)
            <br/>8. To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection.
            <br/>9. To cooperate with governmental agencies and otherwise comply with applicable law.
            <br/>10. To notify you about changes to our Website or any products or services we offer or provide though it.
            <br/>11. To fulfill any other purpose for which you provide it or to which you consent.
            <br/>5. Use of Non-Personally-Identifiable Information. In addition to any of the uses identified for Personally-Identifiable Information, we may also use Non-Personally Identifiable Information to: gather demographic and preference information. We may also share this information with our authorized affiliated businesses and advertisers for these purposes. We may also publish this information for promotional purposes or as a representative audience for advertisers.
            <br/>6. Sharing of Information that Chyp Receives. We neither rent nor sell your Personally Identifiable Information to anyone. We share such personal information only as follows.
            <br/>1. Third-Party Businesses. We may affiliate with a variety of businesses and provide or promote products jointly with those affiliated businesses or allow those third parties to market their products or services to you if you have not opted out of these disclosures.
            <br/>2. Agents/Third-Party Service Providers. We may engage contractors to support our business (“Third-Party Service Providers”). The Third-Party Service Providers may assist us by sending postal mail and e-mail, removing repetitive information from customer lists, performing surveys, tracking clicks, analyzing data, performing legal, accounting, and other administrative functions and website operations, providing marketing assistance, providing search results and links (including paid listings and links), processing credit card payments, and providing customer service. We may also provide your personal information to agents who will use it to verify aggregate usage data that we provide to our affiliated businesses. These agents are not to use your information for any other purposes.
            <br/>3. Promotional Offers. We may send you offers on behalf of other businesses. But when we do so, we will not give the other business your name and address. If you do not wish to receive these offers, please notify us by e-mail at info@cheddarup.com.
            <br/>4. Re-Marketing. We may remarket your information. Remarketing is a way for us to connect with users, based upon your past interactions with our Website. We may hire third-party marketing vendors, such as Google, to perform remarketing services. As a result, such third-party vendors, including Google, may show our ads on sites on the Internet, and may use cookies to serve specific ads based on a user’s prior visits to our Website. Users may opt out of Google’s use of cookies by visiting the Google advertising opt-out page at http://www.google.com/privacy_ads.html. We cannot control how Google or other third parties use information stored in cookies.
            <br/>5. Discussion Forums, Blogs, Comments, and User-Generated Content. The information you provide us in connection with your user profile and any content you post to the Website may be used to facilitate and provide your requested services within the Website or your requested services through other websites (such as if you request our assistance with any affiliated businesses). Any personal information or content that you voluntarily disclose online (on discussion boards, in blogs, comments, messages, and chat areas, and within your public profile page, etc.) becomes publicly available and can be collected and used by us and others; such information may be redistributed through the Internet and other media channels and may be viewed by the general public.
            <br/>6. Communication About the Website or in Response to Your Requests. As part of the Website and our services, you may receive e-mail and other communications relating to your use of the Website or your user account. You acknowledge and agree that by posting information on the Website or otherwise using the Website, we and our agents may send you e-mail or otherwise contact you as we determine necessary in our sole discretion related to your use of the Website. We may use your e-mail address to send updates, a newsletter, or other news regarding the Website or our offerings.
            <br/>7. Business Transfers. In some cases, we may engage in a merger, divestiture, restructuring, reorganization, dissolution or other sale or transfer of some or all of Chyp’s assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding. In these types of transactions, customer information is typically one of the business assets transferred, and you consent to that transfer as well as the successor entity’s continued use of your information as provided in this Policy. We may also disclose your information to our subsidiaries, a parent company, or other entities under common control with us.
            <br/>8. Protection of Chyp and Others. We may release personal information when we believe in good faith that release is necessary to: enforce or apply our Terms of Use and other agreements; enforce our ability to bill and collect for the products or services we provide; or to protect the rights, property, or safety of Chyp, our employees, our users, or others. This includes but is not limited to exchanging information with other companies and organizations for fraud protection and credit risk reduction.
            <br/>9. With Your Consent. We may share your information with your consent or to fulfill the purpose for which you provided it.
            <br/>10. Aggregate Information. We may disclose aggregated information about our users, and information that does not identify any individual, without restriction.
            <br/>11. Court Orders or Legal Process. We may share information to comply with any court order, law or legal process, or as we deem necessary to respond to any government or regulatory request.
            <br/>7. User Choices on Collection and Use of Information. You can always opt not to disclose information, but then you may be unable to use certain features on our Website.
            <br/>1. How Do I Opt Out, What Information Can I Access, and What Can I Delete? Contact chypit.ca@gmail.com to retrieve your personal information and request deletion.
            <br/>2. Deletion of Account. You may request deletion of your Chyp account by contacting chypit.ca@gmail.com But as noted above, even after your account has been disabled, information may remain in our records after deletion of your account.
            <br/>3. E-Mails from Chyp. As a condition of your use of the Website or participation in our offerings, we may send you administrative and promotional e-mails. We may send you information regarding your account activity as well as updates about our offerings. You cannot opt-out of administrative e-mails, which relate to your activity on the Website, activity regarding your account, requests or inquiries, or purchases of products and services. If you no longer wish to receive promotional e-mails, you may unsubscribe from these by e-mailing us at chypit.ca@gmail.com, by writing to us at the address contained in Section 13, or by hitting the “unsubscribe” button at the bottom of any of our e-mails. When contacting us, please indicate your name, e-mail address, and what promotional e-mails you do not want to receive. Please note that if you do not want to receive legal notices from us, such as this Privacy Policy, those legal notices will still govern your use of the Chyp Website, and you are responsible for reviewing such legal notices for changes.
            <br/>8. Security of Information. We take security seriously and take numerous precautions to protect the security of Personally Identifiable Information. You can access your Personally Identifiable Information on our Website through a password and your e-mail address. This password is encrypted. We recommend that you do not share your password with anyone. In addition, your Personally Identifiable Information resides on a secure server that only selected personnel and contractors have access to. Certain sensitive information, such as purchase and credit card information for purchases made through our site, is transmitted using Secure Socket Layer (SSL) technology to help ensure that your Personally Identifiable Information is safe as it is transmitted to us. We try to protect user information so that the user account information is kept private, but no data transmission over the Internet or any wireless network can be guaranteed to be 100% secure, and other factors may undermine the security of your information, including unauthorized use or entry, hardware or software failures, and other factors. Accordingly, while we employ reasonable security measures to protect data and seek to affiliate with companies that do the same, we cannot guarantee the security of account information transmitted to or from the Website, and are not responsible for the actions of any third parties that may receive any such information. For more information about the security measures we use in connection with the Website, please contact us at chypit.ca@gmail.com.
            <br/>9. Third-Party Websites. This Privacy Policy only addresses the use and disclosure of information we collect from you on www.chyp.ca. Chyp may permit you to link to other websites on the Internet, and those other websites may contain links to the Chyp Website. These other websites are not under Chyp’s control, and any links to those websites do not constitute an endorsement by Chyp of those other websites or their services, or otherwise suggest any agency or partnership between Chyp and those or any other third parties. Any other websites that may be accessible through this Website have their own privacy policies, and data collection and use practices. This Privacy Policy does not cover any third-party policies and practices. If you click through to any other websites, you should review the privacy policies of those websites. We are not responsible for the policies or practices of third parties.
            <br/>10. Does the Website Collect Information from Children Under 18? Our Website and our offerings are not intended for children under the age of 18. We do not knowingly collect or solicit personal information from anyone under the age of 18 or knowingly allow persons under 18 to register. If you are under 18, you are prohibited from using or providing any information on or through this Website, engaging in any of the interactive or public comment features of this Website, or providing any information about yourself to us; please do not attempt to register or send any information about yourself to us, including your name, address, telephone number, any screen name or user name you may use, or e-mail address. If we learn that we have collected or received personal information from a child under 18 without verification of parental consent, we will delete that information. If you believe that we might have any information from or about a child under 18, please contact us at chypit.ca@gmail.com.
            <br/>11. Conditions of Use. If you decide to visit the Chyp Website, your visit and any possible dispute over privacy is subject to this Privacy Policy and our Terms of Use, including limitations on damages, arbitration of disputes, and application of Colorado state law.
            <br/>12. Changes to this Policy. We may amend our Privacy Policy and Terms of Use from time to time in our sole discretion. If we do make changes, we will notify you by posting an announcement on the Website or sending you an e-mail so you are always aware of what information we collect, how we use it, and under what circumstances, if any, we will disclose it. Any changes that are less restrictive of your privacy will apply only to information gathered after we have provided you with notice of the change. Unless stated otherwise (such as during a specific process or activity on the website), our current Privacy Policy applies to all information that we have about you and your account. We stand behind the promises we make, however, and will never materially change our policies and practices to make them less protective of customer information collected in the past without the consent of affected customers.
            <br/>13. Questions/How to Contact Chyp. If you have any questions or concerns regarding: this Privacy Policy, our practices with respect to personal information, or your ability delete your personal information from our database or to stop receiving communications from us, please notify us at:
            <br/>E-mail: chypit.ca@gmail.com
            Should you contact us by any of the above means, please provide sufficient information for us to identify your account. Your privacy is important to use, and we will make every effort to resolve your concerns as soon as reasonably possible.
            Effective Date: March 28, 2018
            </p>
      </div>
    )
  }
}
